// Code generated by protoc-gen-go. DO NOT EDIT.
// source: currencyrates.proto

package currencyrates

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRateRequest struct {
	//@inject_tag: validate:"required,alpha,len=3"
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty" validate:"required,alpha,len=3"`
	//@inject_tag: validate:"required,alpha,len=3"
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty" validate:"required,alpha,len=3"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *GetRateRequest) Reset()         { *m = GetRateRequest{} }
func (m *GetRateRequest) String() string { return proto.CompactTextString(m) }
func (*GetRateRequest) ProtoMessage()    {}
func (*GetRateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d90eccbc6e715cb5, []int{0}
}

func (m *GetRateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRateRequest.Unmarshal(m, b)
}
func (m *GetRateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRateRequest.Marshal(b, m, deterministic)
}
func (m *GetRateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRateRequest.Merge(m, src)
}
func (m *GetRateRequest) XXX_Size() int {
	return xxx_messageInfo_GetRateRequest.Size(m)
}
func (m *GetRateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRateRequest proto.InternalMessageInfo

func (m *GetRateRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *GetRateRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type GetCentralBankRateRequest struct {
	//@inject_tag: validate:"required,alpha,len=3"
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty" validate:"required,alpha,len=3"`
	//@inject_tag: validate:"required,alpha,len=3"
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty" validate:"required,alpha,len=3"`
	//@inject_tag: validate:"required"
	Datetime             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=datetime,proto3" json:"datetime,omitempty" validate:"required"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *GetCentralBankRateRequest) Reset()         { *m = GetCentralBankRateRequest{} }
func (m *GetCentralBankRateRequest) String() string { return proto.CompactTextString(m) }
func (*GetCentralBankRateRequest) ProtoMessage()    {}
func (*GetCentralBankRateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d90eccbc6e715cb5, []int{1}
}

func (m *GetCentralBankRateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCentralBankRateRequest.Unmarshal(m, b)
}
func (m *GetCentralBankRateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCentralBankRateRequest.Marshal(b, m, deterministic)
}
func (m *GetCentralBankRateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCentralBankRateRequest.Merge(m, src)
}
func (m *GetCentralBankRateRequest) XXX_Size() int {
	return xxx_messageInfo_GetCentralBankRateRequest.Size(m)
}
func (m *GetCentralBankRateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCentralBankRateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCentralBankRateRequest proto.InternalMessageInfo

func (m *GetCentralBankRateRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *GetCentralBankRateRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *GetCentralBankRateRequest) GetDatetime() *timestamp.Timestamp {
	if m != nil {
		return m.Datetime
	}
	return nil
}

type RateData struct {
	//@inject_tag: validate:"required,hexadecimal,len=24" json:"id" bson:"_id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" validate:"required,hexadecimal,len=24" bson:"_id"`
	//@inject_tag: validate:"required,alpha,len=6" json:"created_at" bson:"created_at"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at" validate:"required,alpha,len=6" bson:"created_at"`
	//@inject_tag: validate:"required,alpha,len=6" json:"pair" bson:"pair"
	Pair string `protobuf:"bytes,3,opt,name=pair,proto3" json:"pair" validate:"required,alpha,len=6" bson:"pair"`
	//@inject_tag: validate:"required,numeric,gt=0" json:"rate" bson:"rate"
	Rate float64 `protobuf:"fixed64,4,opt,name=rate,proto3" json:"rate" validate:"required,numeric,gt=0" bson:"rate"`
	//@inject_tag: validate:"required,alpha" json:"source" bson:"source"
	Source               string   `protobuf:"bytes,5,opt,name=source,proto3" json:"source" validate:"required,alpha" bson:"source"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *RateData) Reset()         { *m = RateData{} }
func (m *RateData) String() string { return proto.CompactTextString(m) }
func (*RateData) ProtoMessage()    {}
func (*RateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d90eccbc6e715cb5, []int{2}
}

func (m *RateData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateData.Unmarshal(m, b)
}
func (m *RateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateData.Marshal(b, m, deterministic)
}
func (m *RateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateData.Merge(m, src)
}
func (m *RateData) XXX_Size() int {
	return xxx_messageInfo_RateData.Size(m)
}
func (m *RateData) XXX_DiscardUnknown() {
	xxx_messageInfo_RateData.DiscardUnknown(m)
}

var xxx_messageInfo_RateData proto.InternalMessageInfo

func (m *RateData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RateData) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *RateData) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *RateData) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *RateData) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRateRequest)(nil), "currencyrates.GetRateRequest")
	proto.RegisterType((*GetCentralBankRateRequest)(nil), "currencyrates.GetCentralBankRateRequest")
	proto.RegisterType((*RateData)(nil), "currencyrates.RateData")
}

func init() { proto.RegisterFile("currencyrates.proto", fileDescriptor_d90eccbc6e715cb5) }

var fileDescriptor_d90eccbc6e715cb5 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcf, 0x4a, 0xeb, 0x50,
	0x10, 0xc6, 0x6f, 0xd2, 0xde, 0xd2, 0xce, 0xbd, 0x56, 0x38, 0x8a, 0xc6, 0x82, 0x58, 0xb2, 0xca,
	0x2a, 0x85, 0x2a, 0x82, 0x4b, 0x6d, 0x69, 0x44, 0x17, 0x4a, 0xea, 0x5e, 0xa7, 0xc9, 0xb4, 0x84,
	0xfe, 0x39, 0xf1, 0x64, 0xa2, 0xf6, 0x41, 0x7c, 0x02, 0x5f, 0x54, 0xce, 0x69, 0x2b, 0x44, 0x4b,
	0x41, 0xba, 0x9b, 0xcc, 0xf9, 0xf8, 0xbe, 0x5f, 0x66, 0x06, 0xf6, 0xa2, 0x5c, 0x29, 0x9a, 0x45,
	0x73, 0x85, 0x4c, 0x99, 0x9f, 0x2a, 0xc9, 0x52, 0xec, 0x14, 0x9a, 0x8d, 0x93, 0x91, 0x94, 0xa3,
	0x09, 0xb5, 0xcc, 0xe3, 0x20, 0x1f, 0xb6, 0x38, 0x99, 0x52, 0xc6, 0x38, 0x4d, 0x17, 0x7a, 0xf7,
	0x0c, 0xea, 0x01, 0x71, 0x88, 0x4c, 0x21, 0x3d, 0xe7, 0x94, 0xb1, 0x10, 0x50, 0x1e, 0x2a, 0x39,
	0x75, 0xac, 0xa6, 0xe5, 0xd5, 0x42, 0x53, 0x8b, 0x3a, 0xd8, 0x2c, 0x1d, 0xdb, 0x74, 0x6c, 0x96,
	0xee, 0x2b, 0x1c, 0x05, 0xc4, 0x1d, 0x9a, 0xb1, 0xc2, 0xc9, 0x15, 0xce, 0xc6, 0xbf, 0x34, 0x10,
	0xe7, 0x50, 0x8d, 0x91, 0x49, 0xd3, 0x38, 0xa5, 0xa6, 0xe5, 0xfd, 0x6b, 0x37, 0xfc, 0x05, 0xaa,
	0xbf, 0x42, 0xf5, 0x1f, 0x56, 0xa8, 0xe1, 0x97, 0xd6, 0x7d, 0xb7, 0xa0, 0xaa, 0xb3, 0xba, 0xc8,
	0xa8, 0x4d, 0x93, 0x78, 0x19, 0x63, 0x27, 0xb1, 0xb8, 0x00, 0x88, 0x14, 0x21, 0x53, 0xfc, 0x88,
	0x6c, 0xc2, 0x36, 0xdb, 0xd6, 0x96, 0xea, 0x4b, 0xc3, 0x9c, 0x62, 0xa2, 0x0c, 0x4b, 0x2d, 0x34,
	0xb5, 0xee, 0xe9, 0x21, 0x3a, 0xe5, 0xa6, 0xe5, 0x59, 0xa1, 0xa9, 0xc5, 0x01, 0x54, 0x32, 0x99,
	0xab, 0x88, 0x9c, 0xbf, 0x46, 0xb9, 0xfc, 0x6a, 0x7f, 0x94, 0x60, 0xbf, 0x30, 0xf9, 0x3e, 0xa9,
	0x97, 0x24, 0x22, 0xd1, 0x03, 0x08, 0x88, 0xef, 0xde, 0x94, 0xa6, 0x16, 0xc7, 0x7e, 0x71, 0x67,
	0xc5, 0xd1, 0x37, 0x0e, 0xbf, 0x3d, 0xaf, 0xfe, 0xd4, 0xfd, 0x23, 0x6e, 0x61, 0x37, 0x20, 0xbe,
	0xc7, 0x79, 0x96, 0xa7, 0xb4, 0xad, 0xd9, 0xd3, 0xba, 0xf5, 0xf5, 0xa4, 0xea, 0x6a, 0x5b, 0xef,
	0xa7, 0xed, 0xfa, 0x45, 0x6f, 0x4a, 0xb8, 0x86, 0xff, 0x01, 0x71, 0x9f, 0x65, 0x34, 0xde, 0x92,
	0xf5, 0xc6, 0x1c, 0x68, 0x07, 0x55, 0x9c, 0xe2, 0x7c, 0x3b, 0xaf, 0x41, 0xc5, 0x1c, 0xc1, 0xe9,
	0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0xa8, 0x69, 0xf3, 0x3a, 0x03, 0x00, 0x00,
}
