// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: currencyrates.proto

/*
Package currencyrates is a generated protocol buffer package.

It is generated from these files:
	currencyrates.proto

It has these top-level messages:
	GetCurrentRateRequest
	GetCentralBankRateRequest
	RateData
*/
package currencyrates

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CurrencyratesService service

type CurrencyratesService interface {
	GetCurrentRate(ctx context.Context, in *GetCurrentRateRequest, opts ...client.CallOption) (*RateData, error)
	GetCentralBankRateForDate(ctx context.Context, in *GetCentralBankRateRequest, opts ...client.CallOption) (*RateData, error)
}

type currencyratesService struct {
	c    client.Client
	name string
}

func NewCurrencyratesService(name string, c client.Client) CurrencyratesService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "currencyrates"
	}
	return &currencyratesService{
		c:    c,
		name: name,
	}
}

func (c *currencyratesService) GetCurrentRate(ctx context.Context, in *GetCurrentRateRequest, opts ...client.CallOption) (*RateData, error) {
	req := c.c.NewRequest(c.name, "CurrencyratesService.GetCurrentRate", in)
	out := new(RateData)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyratesService) GetCentralBankRateForDate(ctx context.Context, in *GetCentralBankRateRequest, opts ...client.CallOption) (*RateData, error) {
	req := c.c.NewRequest(c.name, "CurrencyratesService.GetCentralBankRateForDate", in)
	out := new(RateData)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CurrencyratesService service

type CurrencyratesServiceHandler interface {
	GetCurrentRate(context.Context, *GetCurrentRateRequest, *RateData) error
	GetCentralBankRateForDate(context.Context, *GetCentralBankRateRequest, *RateData) error
}

func RegisterCurrencyratesServiceHandler(s server.Server, hdlr CurrencyratesServiceHandler, opts ...server.HandlerOption) error {
	type currencyratesService interface {
		GetCurrentRate(ctx context.Context, in *GetCurrentRateRequest, out *RateData) error
		GetCentralBankRateForDate(ctx context.Context, in *GetCentralBankRateRequest, out *RateData) error
	}
	type CurrencyratesService struct {
		currencyratesService
	}
	h := &currencyratesServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CurrencyratesService{h}, opts...))
}

type currencyratesServiceHandler struct {
	CurrencyratesServiceHandler
}

func (h *currencyratesServiceHandler) GetCurrentRate(ctx context.Context, in *GetCurrentRateRequest, out *RateData) error {
	return h.CurrencyratesServiceHandler.GetCurrentRate(ctx, in, out)
}

func (h *currencyratesServiceHandler) GetCentralBankRateForDate(ctx context.Context, in *GetCentralBankRateRequest, out *RateData) error {
	return h.CurrencyratesServiceHandler.GetCentralBankRateForDate(ctx, in, out)
}
