// Code generated by protoc-gen-go. DO NOT EDIT.
// source: currencyrates.proto

package currencyrates

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRateRequest struct {
	//@inject_tag: validate:"required,alpha,len=3"
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty" validate:"required,alpha,len=3"`
	//@inject_tag: validate:"required,alpha,len=3"
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty" validate:"required,alpha,len=3"`
	//@inject_tag: validate:"omitempty,hexadecimal,len=24"
	MerchantId           string   `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty" validate:"omitempty,hexadecimal,len=24"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *GetRateRequest) Reset()         { *m = GetRateRequest{} }
func (m *GetRateRequest) String() string { return proto.CompactTextString(m) }
func (*GetRateRequest) ProtoMessage()    {}
func (*GetRateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d90eccbc6e715cb5, []int{0}
}

func (m *GetRateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRateRequest.Unmarshal(m, b)
}
func (m *GetRateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRateRequest.Marshal(b, m, deterministic)
}
func (m *GetRateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRateRequest.Merge(m, src)
}
func (m *GetRateRequest) XXX_Size() int {
	return xxx_messageInfo_GetRateRequest.Size(m)
}
func (m *GetRateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRateRequest proto.InternalMessageInfo

func (m *GetRateRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *GetRateRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *GetRateRequest) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

type GetCentralBankRateRequest struct {
	//@inject_tag: validate:"required,alpha,len=3"
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty" validate:"required,alpha,len=3"`
	//@inject_tag: validate:"required,alpha,len=3"
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty" validate:"required,alpha,len=3"`
	//@inject_tag: validate:"required"
	Datetime *timestamp.Timestamp `protobuf:"bytes,3,opt,name=datetime,proto3" json:"datetime,omitempty" validate:"required"`
	//@inject_tag: validate:"omitempty,hexadecimal,len=24"
	MerchantId           string   `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty" validate:"omitempty,hexadecimal,len=24"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *GetCentralBankRateRequest) Reset()         { *m = GetCentralBankRateRequest{} }
func (m *GetCentralBankRateRequest) String() string { return proto.CompactTextString(m) }
func (*GetCentralBankRateRequest) ProtoMessage()    {}
func (*GetCentralBankRateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d90eccbc6e715cb5, []int{1}
}

func (m *GetCentralBankRateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCentralBankRateRequest.Unmarshal(m, b)
}
func (m *GetCentralBankRateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCentralBankRateRequest.Marshal(b, m, deterministic)
}
func (m *GetCentralBankRateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCentralBankRateRequest.Merge(m, src)
}
func (m *GetCentralBankRateRequest) XXX_Size() int {
	return xxx_messageInfo_GetCentralBankRateRequest.Size(m)
}
func (m *GetCentralBankRateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCentralBankRateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCentralBankRateRequest proto.InternalMessageInfo

func (m *GetCentralBankRateRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *GetCentralBankRateRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *GetCentralBankRateRequest) GetDatetime() *timestamp.Timestamp {
	if m != nil {
		return m.Datetime
	}
	return nil
}

func (m *GetCentralBankRateRequest) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

type RateData struct {
	//@inject_tag: validate:"required,hexadecimal,len=24" json:"id" bson:"_id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" validate:"required,hexadecimal,len=24" bson:"_id"`
	//@inject_tag: validate:"required,alpha,len=6" json:"created_at" bson:"created_at"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at" validate:"required,alpha,len=6" bson:"created_at"`
	//@inject_tag: validate:"required,alpha,len=6" json:"pair" bson:"pair"
	Pair string `protobuf:"bytes,3,opt,name=pair,proto3" json:"pair" validate:"required,alpha,len=6" bson:"pair"`
	//@inject_tag: validate:"required,numeric,gt=0" json:"rate" bson:"rate"
	Rate float64 `protobuf:"fixed64,4,opt,name=rate,proto3" json:"rate" validate:"required,numeric,gt=0" bson:"rate"`
	//@inject_tag: validate:"required,alpha" json:"source" bson:"source"
	Source               string   `protobuf:"bytes,5,opt,name=source,proto3" json:"source" validate:"required,alpha" bson:"source"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *RateData) Reset()         { *m = RateData{} }
func (m *RateData) String() string { return proto.CompactTextString(m) }
func (*RateData) ProtoMessage()    {}
func (*RateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d90eccbc6e715cb5, []int{2}
}

func (m *RateData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateData.Unmarshal(m, b)
}
func (m *RateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateData.Marshal(b, m, deterministic)
}
func (m *RateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateData.Merge(m, src)
}
func (m *RateData) XXX_Size() int {
	return xxx_messageInfo_RateData.Size(m)
}
func (m *RateData) XXX_DiscardUnknown() {
	xxx_messageInfo_RateData.DiscardUnknown(m)
}

var xxx_messageInfo_RateData proto.InternalMessageInfo

func (m *RateData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RateData) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *RateData) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *RateData) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *RateData) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d90eccbc6e715cb5, []int{3}
}

func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type CorrectionCorridor struct {
	//@inject_tag: validate:"required,numeric,gte=0,lte=1"
	Value                float64  `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty" validate:"required,numeric,gte=0,lte=1"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *CorrectionCorridor) Reset()         { *m = CorrectionCorridor{} }
func (m *CorrectionCorridor) String() string { return proto.CompactTextString(m) }
func (*CorrectionCorridor) ProtoMessage()    {}
func (*CorrectionCorridor) Descriptor() ([]byte, []int) {
	return fileDescriptor_d90eccbc6e715cb5, []int{4}
}

func (m *CorrectionCorridor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CorrectionCorridor.Unmarshal(m, b)
}
func (m *CorrectionCorridor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CorrectionCorridor.Marshal(b, m, deterministic)
}
func (m *CorrectionCorridor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CorrectionCorridor.Merge(m, src)
}
func (m *CorrectionCorridor) XXX_Size() int {
	return xxx_messageInfo_CorrectionCorridor.Size(m)
}
func (m *CorrectionCorridor) XXX_DiscardUnknown() {
	xxx_messageInfo_CorrectionCorridor.DiscardUnknown(m)
}

var xxx_messageInfo_CorrectionCorridor proto.InternalMessageInfo

func (m *CorrectionCorridor) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type CorrectionRule struct {
	// @inject_tag: validate:"required,hexadecimal,len=24" json:"id" bson:"_id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" validate:"required,hexadecimal,len=24" bson:"_id"`
	//@inject_tag: validate:"omitempty,hexadecimal,len=24" json:"merchant_id" bson:"merchant_id"
	MerchantId string `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id" validate:"omitempty,hexadecimal,len=24" bson:"merchant_id"`
	//@inject_tag: validate:"required,oneof=oxr paysuper centralbanks stock cardpay" json:"rate_type" bson:"rate_type"
	RateType string `protobuf:"bytes,3,opt,name=rate_type,json=rateType,proto3" json:"rate_type" validate:"required,oneof=oxr paysuper centralbanks stock cardpay" bson:"rate_type"`
	// @inject_tag: validate:"omitempty,numeric,gte=-100,lte=100" json:"common_correction" bson:"common_correction"
	CommonCorrection float64 `protobuf:"fixed64,4,opt,name=common_correction,json=commonCorrection,proto3" json:"common_correction" validate:"omitempty,numeric,gte=-100,lte=100" bson:"common_correction"`
	// @inject_tag: validate:"omitempty,dive,keys,alpha,len=6,endkeys,gte=-100,lte=100" json:"pair_correction" bson:"pair_correction"
	PairCorrection map[string]float64 `protobuf:"bytes,5,rep,name=pair_correction,json=pairCorrection,proto3" json:"pair_correction" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3" validate:"omitempty,dive,keys,alpha,len=6,endkeys,gte=-100,lte=100" bson:"pair_correction"`
	// @inject_tag: validate:"required" json:"created_at"  bson:"created_at"
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at" validate:"required" bson:"created_at"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *CorrectionRule) Reset()         { *m = CorrectionRule{} }
func (m *CorrectionRule) String() string { return proto.CompactTextString(m) }
func (*CorrectionRule) ProtoMessage()    {}
func (*CorrectionRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_d90eccbc6e715cb5, []int{5}
}

func (m *CorrectionRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CorrectionRule.Unmarshal(m, b)
}
func (m *CorrectionRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CorrectionRule.Marshal(b, m, deterministic)
}
func (m *CorrectionRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CorrectionRule.Merge(m, src)
}
func (m *CorrectionRule) XXX_Size() int {
	return xxx_messageInfo_CorrectionRule.Size(m)
}
func (m *CorrectionRule) XXX_DiscardUnknown() {
	xxx_messageInfo_CorrectionRule.DiscardUnknown(m)
}

var xxx_messageInfo_CorrectionRule proto.InternalMessageInfo

func (m *CorrectionRule) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CorrectionRule) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *CorrectionRule) GetRateType() string {
	if m != nil {
		return m.RateType
	}
	return ""
}

func (m *CorrectionRule) GetCommonCorrection() float64 {
	if m != nil {
		return m.CommonCorrection
	}
	return 0
}

func (m *CorrectionRule) GetPairCorrection() map[string]float64 {
	if m != nil {
		return m.PairCorrection
	}
	return nil
}

func (m *CorrectionRule) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CorrectionRuleRequest struct {
	//@inject_tag: validate:"omitempty,hexadecimal,len=24"
	MerchantId string `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty" validate:"omitempty,hexadecimal,len=24"`
	//@inject_tag: validate:"required,oneof=oxr paysuper centralbank stock cardpay"
	RateType             string   `protobuf:"bytes,2,opt,name=rate_type,json=rateType,proto3" json:"rate_type,omitempty" validate:"required,oneof=oxr paysuper centralbank stock cardpay"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *CorrectionRuleRequest) Reset()         { *m = CorrectionRuleRequest{} }
func (m *CorrectionRuleRequest) String() string { return proto.CompactTextString(m) }
func (*CorrectionRuleRequest) ProtoMessage()    {}
func (*CorrectionRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d90eccbc6e715cb5, []int{6}
}

func (m *CorrectionRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CorrectionRuleRequest.Unmarshal(m, b)
}
func (m *CorrectionRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CorrectionRuleRequest.Marshal(b, m, deterministic)
}
func (m *CorrectionRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CorrectionRuleRequest.Merge(m, src)
}
func (m *CorrectionRuleRequest) XXX_Size() int {
	return xxx_messageInfo_CorrectionRuleRequest.Size(m)
}
func (m *CorrectionRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CorrectionRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CorrectionRuleRequest proto.InternalMessageInfo

func (m *CorrectionRuleRequest) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *CorrectionRuleRequest) GetRateType() string {
	if m != nil {
		return m.RateType
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRateRequest)(nil), "currencyrates.GetRateRequest")
	proto.RegisterType((*GetCentralBankRateRequest)(nil), "currencyrates.GetCentralBankRateRequest")
	proto.RegisterType((*RateData)(nil), "currencyrates.RateData")
	proto.RegisterType((*EmptyResponse)(nil), "currencyrates.EmptyResponse")
	proto.RegisterType((*CorrectionCorridor)(nil), "currencyrates.CorrectionCorridor")
	proto.RegisterType((*CorrectionRule)(nil), "currencyrates.CorrectionRule")
	proto.RegisterMapType((map[string]float64)(nil), "currencyrates.CorrectionRule.PairCorrectionEntry")
	proto.RegisterType((*CorrectionRuleRequest)(nil), "currencyrates.CorrectionRuleRequest")
}

func init() { proto.RegisterFile("currencyrates.proto", fileDescriptor_d90eccbc6e715cb5) }

var fileDescriptor_d90eccbc6e715cb5 = []byte{
	// 600 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xad, 0xdd, 0xa6, 0x6a, 0xa7, 0x5f, 0xd3, 0x7e, 0xdb, 0x16, 0x42, 0xa0, 0x6a, 0xb1, 0xb8,
	0xa8, 0x40, 0x72, 0x45, 0x90, 0x10, 0x70, 0x17, 0xd2, 0x36, 0xfc, 0x5c, 0x50, 0x39, 0x2d, 0x17,
	0x5c, 0x10, 0x36, 0xf6, 0xb4, 0x58, 0x89, 0xbd, 0x66, 0x3d, 0xae, 0xf0, 0x83, 0x20, 0xf1, 0x36,
	0x3c, 0x0d, 0xef, 0x81, 0x76, 0x63, 0x37, 0xb5, 0x13, 0x8c, 0xaa, 0xdc, 0xcd, 0xce, 0x1e, 0xcd,
	0x9c, 0x73, 0x76, 0x66, 0x61, 0xcb, 0x4d, 0xa4, 0xc4, 0xd0, 0x4d, 0x25, 0x27, 0x8c, 0xed, 0x48,
	0x0a, 0x12, 0x6c, 0xbd, 0x90, 0x6c, 0xee, 0x5d, 0x0a, 0x71, 0x39, 0xc2, 0x43, 0x7d, 0x39, 0x48,
	0x2e, 0x0e, 0xc9, 0x0f, 0x30, 0x26, 0x1e, 0x44, 0x63, 0xbc, 0x75, 0x0e, 0xf5, 0x2e, 0x92, 0xc3,
	0x09, 0x1d, 0xfc, 0x96, 0x60, 0x4c, 0x8c, 0xc1, 0xd2, 0x85, 0x14, 0x41, 0xc3, 0xd8, 0x37, 0x0e,
	0x56, 0x1d, 0x1d, 0xb3, 0x3a, 0x98, 0x24, 0x1a, 0xa6, 0xce, 0x98, 0x24, 0xd8, 0x1e, 0xac, 0x05,
	0x28, 0xdd, 0xaf, 0x3c, 0xa4, 0xbe, 0xef, 0x35, 0x16, 0xf5, 0x05, 0xe4, 0xa9, 0xb7, 0x9e, 0xf5,
	0xd3, 0x80, 0x7b, 0x5d, 0xa4, 0x0e, 0x86, 0x24, 0xf9, 0xe8, 0x35, 0x0f, 0x87, 0xb7, 0x6d, 0xf1,
	0x1c, 0x56, 0x3c, 0x4e, 0xa8, 0xf8, 0xea, 0xfa, 0x6b, 0xad, 0xa6, 0x3d, 0x16, 0x63, 0xe7, 0x62,
	0xec, 0xb3, 0x5c, 0x8c, 0x73, 0x8d, 0x2d, 0x53, 0x5b, 0x9a, 0xa2, 0xf6, 0xc3, 0x80, 0x15, 0x45,
	0xe6, 0x88, 0x13, 0x57, 0x5d, 0x7d, 0x2f, 0xe3, 0x61, 0xfa, 0x1e, 0x7b, 0x09, 0xe0, 0x4a, 0xe4,
	0x84, 0x5e, 0x9f, 0x93, 0x66, 0x53, 0xdd, 0x77, 0x35, 0x43, 0xb7, 0xb5, 0xa8, 0x88, 0xfb, 0x32,
	0x33, 0x43, 0xc7, 0x2a, 0xa7, 0xde, 0x41, 0xb3, 0x30, 0x1c, 0x1d, 0xb3, 0x3b, 0xb0, 0x1c, 0x8b,
	0x44, 0xba, 0xd8, 0xa8, 0x69, 0x64, 0x76, 0xb2, 0x36, 0x60, 0xfd, 0x38, 0x88, 0x28, 0x75, 0x30,
	0x8e, 0x44, 0x18, 0xa3, 0xf5, 0x18, 0x58, 0x47, 0x48, 0x89, 0x2e, 0xf9, 0x22, 0x54, 0x91, 0xef,
	0x09, 0xc9, 0xb6, 0xa1, 0x76, 0xc5, 0x47, 0x09, 0x6a, 0xd2, 0x86, 0x33, 0x3e, 0x58, 0xbf, 0x4d,
	0xa8, 0x4f, 0xc0, 0x4e, 0x32, 0xc2, 0x29, 0x69, 0x25, 0x63, 0xcc, 0xb2, 0x31, 0xec, 0x3e, 0xac,
	0x2a, 0x82, 0x7d, 0x4a, 0x23, 0xcc, 0x54, 0xac, 0xa8, 0xc4, 0x59, 0x1a, 0x21, 0x7b, 0x02, 0xff,
	0xbb, 0x22, 0x08, 0x44, 0xd8, 0x77, 0xaf, 0xdb, 0x64, 0xb2, 0x36, 0xc7, 0x17, 0x93, 0xf6, 0xec,
	0x13, 0x6c, 0x28, 0xf9, 0x37, 0xa1, 0xb5, 0xfd, 0xc5, 0x83, 0xb5, 0xd6, 0x53, 0xbb, 0x38, 0xb3,
	0x45, 0xca, 0xf6, 0x29, 0xf7, 0xe5, 0x24, 0x75, 0x1c, 0x92, 0x4c, 0x9d, 0x7a, 0x54, 0x48, 0x96,
	0x5e, 0x68, 0xf9, 0x16, 0x2f, 0xd4, 0x6c, 0xc3, 0xd6, 0x8c, 0x0e, 0x6c, 0x13, 0x16, 0x87, 0x98,
	0x66, 0x4e, 0xa9, 0x70, 0xe2, 0xb1, 0x79, 0xc3, 0xe3, 0x57, 0xe6, 0x0b, 0xc3, 0x3a, 0x87, 0x9d,
	0x22, 0xe7, 0x7c, 0xa4, 0x4b, 0xee, 0x1a, 0xd5, 0xee, 0x9a, 0x45, 0x77, 0x5b, 0xbf, 0x6a, 0xb0,
	0x5d, 0x70, 0xa6, 0x87, 0xf2, 0xca, 0x77, 0x91, 0x9d, 0x00, 0x74, 0x91, 0x3e, 0x7c, 0x97, 0x6a,
	0x62, 0xd9, 0x6e, 0xc9, 0xbe, 0xe2, 0xe6, 0x36, 0xef, 0x96, 0xae, 0xf3, 0x29, 0xb7, 0x16, 0xd8,
	0x7b, 0xd8, 0xe8, 0x22, 0x9d, 0xf2, 0x34, 0x4e, 0x22, 0x9c, 0xb7, 0xd8, 0x97, 0x59, 0xbb, 0x7d,
	0x22, 0xe4, 0x91, 0x2a, 0x7b, 0x30, 0x5d, 0x76, 0xf6, 0x2f, 0x50, 0xd5, 0xe1, 0x0d, 0xfc, 0xd7,
	0x45, 0xea, 0x91, 0x70, 0x87, 0x73, 0x72, 0x7d, 0xa7, 0xff, 0xb7, 0x0e, 0x97, 0x5e, 0xc4, 0xd3,
	0x39, 0x6b, 0x7d, 0x86, 0x9d, 0x0c, 0x5c, 0x5a, 0xb5, 0x47, 0x95, 0x63, 0x9d, 0x57, 0xde, 0xad,
	0x44, 0x59, 0x0b, 0x6c, 0x00, 0xbb, 0xbd, 0xc9, 0x23, 0xcd, 0xd8, 0xfd, 0x87, 0x7f, 0xad, 0x90,
	0x43, 0x9a, 0x0f, 0x4a, 0x90, 0xe2, 0x97, 0xb2, 0xc0, 0x3e, 0xc2, 0x4e, 0xdb, 0xf3, 0x66, 0x68,
	0xa8, 0x66, 0xf7, 0xaf, 0xba, 0x83, 0x65, 0xbd, 0x7a, 0xcf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x48, 0xd2, 0xb1, 0xd3, 0x95, 0x06, 0x00, 0x00,
}
